name: Non functional tests

on:
  workflow_dispatch:
    inputs:
      url:
        description: Enter single page or sitemap.xml URL
        required: true
      run-accessibility:
        type: boolean
        description: Run accessibility checks?
        required: false
      run-security:
        type: boolean
        description: Run security checks?
        required: false
      run-performance:
        type: boolean
        description: Run performance checks?
        required: false
      run-link:
        type: boolean
        description: Run link checks?
        required: false
      run-spelling:
        type: boolean
        description: Run spelling checks?
        required: false

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Show github json
        run: |
          echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
      - name: Input values
        run: |
          echo "Page(s) under test: ${{ github.event.inputs.url }}"
          echo "run-accessibility: ${{ github.event.inputs.run-accessibility }}"
          echo "run-security: ${{ github.event.inputs.run-security }}"
          echo "run-performance: ${{ github.event.inputs.run-performance }}"
          echo "run-link: ${{ github.event.inputs.run-link }}"
          echo "run-spelling: ${{ github.event.inputs.run-spelling }}"
